# Generated by Django 3.2.8 on 2021-11-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialdate', models.DateField()),
                ('finaldate', models.DateField()),
                ('room_no', models.IntegerField(null=True)),
                ('hotelName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel')),
            ],
        ),
    ]
