# Generated by Django 3.2.8 on 2021-11-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hotelName',
            new_name='name',
        ),
    ]
