# Generated by Django 3.2.8 on 2021-11-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_hotelname_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='finaldate',
            new_name='checkindate',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='initialdate',
            new_name='checkoutdate',
        ),
        migrations.AddField(
            model_name='room',
            name='waiting',
            field=models.BooleanField(default=False),
        ),
    ]
