# Generated by Django 3.2.8 on 2021-11-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20211116_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='checkindate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='checkoutdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
