# Generated by Django 3.2.8 on 2021-11-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20211118_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotelName',
            field=models.CharField(max_length=200),
        ),
    ]
