# Generated by Django 3.2.8 on 2021-11-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_hotel_hotelname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='checkindate',
            new_name='checkin_date',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='checkoutdate',
            new_name='checkout_date',
        ),
    ]
