# Generated by Django 3.2.8 on 2021-11-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20211120_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='checkin_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='checkout_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
