# Generated by Django 3.2.8 on 2021-11-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20211120_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single-AC', 'Single-AC'), ('Double-AC', 'Double-AC'), ('Single-NON-AC', 'Single NON-AC'), ('Double-NON-AC', 'Double-NON-AC')], default='Single-AC', max_length=20),
        ),
    ]
